[package]
name = "bevy-hid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.4.2"
hidasp = { git = "https://github.com/fishykins/hidasp" }
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = ["bevy_asset"] }